apiVersion: v1
kind: ConfigMap
metadata:
  name: payment-config
  namespace: payment-system
data:
  REDIS_HOST: redis
  REDIS_PORT: "6379"

  USER_SERVICE_URL: http://user-service:8081
  TRANSACTION_SERVICE_URL: http://transaction-service:8082
  NOTIFICATION_SERVICE_URL: http://notification-service:8084
  REWARD_SERVICE_URL: http://reward-service:8085

  WALLET_SERVICE_URL: http://wallet-service:8088/api/v1/wallets
  SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092